- name: apply common configuration to all nodes
  hosts: all
  remote_user: root

  roles:
    - common

- name: setup openstack dependencies on compute nodes
  hosts: compute
  remote_user: root

  roles:
    - setup