- name: Add apt repo
  apt_repository:
    repo: cloud-archive:rocky
    state: present

- name: Update cache
  apt:
   update_cache: yes

- name: Install OpenStack packages
  apt:
    name: "{{ packages }}"
    state: present
    vars:
      packages:
      - software-properties-common
      - python-openstackclient